name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: ['x86_64', 'aarch64']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: |
        sudo apt-get update -y
        if [ "${{ matrix.target }}" = "x86_64" ]; then
          sudo apt-get install -y g++-x86-64-linux-gnu
        else
          sudo apt-get install -y g++-${{ matrix.target }}-linux-gnu
        fi

    - name: Build
      run: make ${{ matrix.target }}

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.7.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./build/release/kcsh-*
        file_glob: true
        overwrite: true
        tag: ${{ github.ref }}-${{ steps.vars.outputs.sha_short }}

